// Instale a extensão REST Client para efetuar os testes
// Teste da API REST de agendamentos
@baseURL = http://localhost:3000/api/agendamentos
@id = 680adafaac63103ade01df8c

###
// GET - Lista todos os agendamentos (por padrão apenas 10 por página)
GET {{baseURL}}
Content-Type: application/json
###
// GET - Lista o agendamento pelo ID
GET {{baseURL}}/{{id}}
Content-Type: application/json

###
// POST - Insere um novo agendamento
POST {{baseURL}}
Content-Type: application/json

{
    "client_name": "Louis",
    "barber_name": "Pedro Oliveira",
    "services":[
        {"name":"design de sobrancelha","price":0.23},
        {"name":"tratamento capilar","price":62.27},
        {"name":"massagem relaxante", "price" : 100.00}
    ],
    "date": "2025-05-13 22:03:03"
}

###
// PUT - Altera um agendamento já existente
PUT {{baseURL}}/{{id}}
Content-Type: application/json

{
    "date" : "22/10/2023"
}

###
// DELETE - Remove o agendamento pelo id
DELETE {{baseURL}}/{{id}}
Content-Type: application/json

###
//PATCH - ATUALIZA O STATUS DO AGENDAMENTO para cancelado(utilizando data de teste)
PATCH {{baseURL}}/{{id}}/cancelar

###
//PATCH - ATUALIZA O STATUS DO AGENDAMENTO para confirmado(utilizando data de teste)
PATCH {{baseURL}}/{{id}}/confirmar

###
// GET - Lista todos os agendamentos (com limite de 2)
GET {{baseURL}}?limit=2
Content-Type: application/json

###
// GET - Lista todos os agendamentos em ordem desc (começa da data mais distante até a mais próxima)
GET {{baseURL}}?order=desc
Content-Type: application/json

###
// GET - Lista de agendamentos com o barbeiro (query param barber_name)
GET {{baseURL}}?barber_name=Pedro Oliveira
Content-Type: application/json

###
// GET - Lista de agendamentos ordenado por nome do cliente (query param sort)
GET {{baseURL}}?sort=client_name
Content-Type: application/json

###
// GET - Lista de agendamentos para serviço de depilação facial
GET {{baseURL}}?service=corteinfantil
Content-Type: application/json

###
// GET - Lista de agendamentos para serviço de depilação facial
GET {{baseURL}}?date=2024-06-04 22:15:38
Content-Type: application/json